import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "mahyar",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: true,
    },
    {
      name: "ali",
      email: "user@example.com",
      password: bcrypt.hashSync("12342356", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Slim Shirt",
      category: "shirts",
      image: "./images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality producs",
    },
    {
      name: "Puma Slim Shirt",
      category: "shirts",
      image: "./images/p2.jpg",
      price: 125,
      countInStock: 20,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "high quality producs",
    },
    {
      name: "Zara Slim Shirt",
      category: "shirts",
      image: "./images/p3.jpg",
      price: 100,
      countInStock: 0,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality producs",
    },
    {
      name: "Nike Slim pants",
      category: "shirts",
      image: "./images/p4.jpg",
      price: 110,
      countInStock: 5,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality producs",
    },
    {
      name: "Addidas Slim Shirt",
      category: "shirts",
      image: "./images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality producs",
    },
    {
      name: "Nike  Shirt",
      category: "shirts",
      image: "./images/p1.jpg",
      price: 120,
      countInStock: 0,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality producs",
    },
  ],
};
export default data;
