const data = {
  products: [
    {
      _id: 1,
      name: "Nike Slim Shirt",
      category: "shirts",
      image: "./images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality producs",
    },
    {
      _id: 2,
      name: "Nike Slim Shirt",
      category: "shirts",
      image: "./images/p2.jpg",
      price: 125,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "high quality producs",
    },
    {
      _id: 3,
      name: "Nike Slim Shirt",
      category: "shirts",
      image: "./images/p3.jpg",
      price: 100,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality producs",
    },
    {
      _id: 4,
      name: "Nike Slim Shirt",
      category: "shirts",
      image: "./images/p4.jpg",
      price: 110,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality producs",
    },
    {
      _id: 5,
      name: "Nike Slim Shirt",
      category: "shirts",
      image: "./images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality producs",
    },
    {
      _id: 6,
      name: "Nike Slim Shirt",
      category: "shirts",
      image: "./images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality producs",
    },
  ],
};
export default data;
